export enum FileSearchFailureReason {
  INVALID_REQUEST = 'INVALID_REQUEST',
  INITIALIZATION_FAILED = 'INITIALIZATION_FAILED',
  NOT_INITIALIZED = 'NOT_INITIALIZED',
  SUPERSEDED = 'SUPERSEDED',
  INTERNAL = 'INTERNAL',
}
