export enum TerminalActionType {
  SEND = 'send',
  EXIT = 'exit',
  HELP = 'help',
  RESET = 'reset',
  NEW_CHAT = 'new-chat',
  LIST_CHATS = 'list-chats',
  SWITCH_CHAT = 'switch-chat',
  RENAME_CHAT = 'rename-chat',
  USAGE = 'usage',
  TRACE = 'trace',
  ACCOUNT = 'account',
  LOGIN = 'login',
  LOGOUT = 'logout',
  REVIEW = 'review',
  ACCEPT_ALL = 'accept-all',
  REJECT_ALL = 'reject-all',
  UNKNOWN_COMMAND = 'unknown-command',
}
