export enum EditFailureReason {
  MALFORMED = 'MALFORMED',
  EMPTY = 'EMPTY',
  INCONSISTENT = 'INCONSISTENT',
  AMBIGUOUS = 'AMBIGUOUS',
  UNSUPPORTED = 'UNSUPPORTED',
  LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',
  STALE = 'STALE',
  DECISION_CONFLICT = 'DECISION_CONFLICT',
  PERSISTENCE = 'PERSISTENCE',
  ACTIVE_REVIEW_LIMIT = 'ACTIVE_REVIEW_LIMIT',
}
