export enum ContextAttachmentFailureReason {
  INVALID_REFERENCE = 'INVALID_REFERENCE',
  FILE_COUNT_LIMIT_EXCEEDED = 'FILE_COUNT_LIMIT_EXCEEDED',
  FILE_SIZE_LIMIT_EXCEEDED = 'FILE_SIZE_LIMIT_EXCEEDED',
  TOTAL_SIZE_LIMIT_EXCEEDED = 'TOTAL_SIZE_LIMIT_EXCEEDED',
  READ_FAILED = 'READ_FAILED',
}
